sudo: false
env:
  - JIT_OPTS='--opt=jit' TARGET_OPTS='target.py'
  - JIT_OPTS='' TARGET_OPTS='target.py'

matrix:
  fast_finish: true 

script:
  - make PYTHON=python build
  - make compile_src
  - make compile_tests
  - make run_built_tests

addons:
  apt:
    packages:
      - libffi-dev
      - libedit-dev
      - libboost-all-dev
      - zlib1g-dev
      - zlib-bin

notifications:
  irc: "chat.freenode.net#pixie-lang"
